### ISSUE TITLE
Failed to parse JSON

### ISSUE THREAD

**Issue by gosvoh** [codex-team/hawk.vite.plugin#5]
Error for each map
```
#11 44.56 🦅 Hawk | (⌐■_■) Sending dist/assets/BqcNzQMh.js.map failed: 
#11 44.56 
#11 44.56 Failed to parse JSON
#11 44.56 
#11 44.56 🦅 Hawk | Map dist/assets/BqcNzQMh.js.map deleted
```

**Comment by TatianaFomina** [comment]
Hello, thank you for issue submission. 
Please, provide some details. 
What project are you using this plugin in?
What does your vite config look like?

**Comment by TatianaFomina** [comment]
Hi, this error was likely related to the infrastructural issue we've had in Hawk. Please check if it's still reproducible

**Comment by gosvoh** [comment]
> Hi, this error was likely related to the infrastructural issue we've had in Hawk. Please check if it's still reproducible

Everything works fine now
